name: 自动部署 Hexo

on:
  push:
    branches:
      - main # 修改为你使用的分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 配置 Node.js 环境
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装 Hexo CLI
        run: |
          npm install hexo-cli -g
          npm install
          npm audit fix # 可选，修复依赖安全漏洞

      - name: 安装 Hexo 插件
        run: |
          npm install hexo-deployer-git hexo-generator-archive hexo-generator-category hexo-generator-feed hexo-generator-index hexo-generator-search hexo-generator-tag \
            hexo-renderer-ejs hexo-renderer-marked hexo-renderer-stylus hexo-server hexo-wordcount --save
          npm audit fix --only=prod # 可选，修复依赖安全漏洞

      - name: 部署博客
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GH_TOKEN }}
          GIT_NAME: ${{ secrets.GIT_NAME }} # 修改为您的用户名或昵称
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }} # 修改为您的邮箱地址
          DEPLOY_BRANCH: gh-pages # 修改为您使用的分支名称
        run: |
          hexo clean
          hexo generate
          cd ./public && \
            git init && \
            git config user.name "miaopasixx" && \
            git config user.email "a13026588708@163.com" && \
            git add . && \
            git commit -m "Deploy by GitHub Actions" && \
            git push -f "git@github.com:miaopasixx/ceshi.git" master:master

      - name: 清理 Node.js 缓存
        run: npm cache clean --force
