name: 自动部署 Hexo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 开始运行
        uses: actions/checkout@v1

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 配置 Git 环境
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "miaopasixx"
          git config --global user.email "a13026588708@163.com"

      - name: 安装 Hexo CI
        run: |
          export TZ='Asia/Shanghai'
          npm i -g hexo-cli
          npm i

      - name: 安装插件
        run: |
          npm install --save add@2.0.6
          npm install --save artplayer@4.6.2
          npm install --save hexo-abbrlink@2.2.1
          npm install --save hexo-butterfly-charts@1.1.3
          npm install --save hexo-butterfly-envelope@1.0.15
          npm install --save hexo-butterfly-tag-plugins-plus@1.0.17
          npm install --save hexo-deployer-git@4.0.0
          npm install --save hexo-filter-fcircle-anzhiyu@1.1.5
          npm install --save hexo-generator-archive@2.0.0
          npm install --save hexo-generator-category@2.0.0
          npm install --save hexo-generator-feed@3.0.0
          npm install --save hexo-generator-index@3.0.0
          npm install --save hexo-generator-searchdb@1.4.1
          npm install --save hexo-generator-tag@2.0.0
          npm install --save hexo-renderer-ejs@2.0.0
          npm install --save hexo-renderer-kramed@0.1.4
          npm install --save hexo-renderer-pug@3.0.0
          npm install --save hexo-renderer-stylus@2.1.0
          npm install --save hexo-server@3.0.0
          npm install --save hexo-tag-mtime@0.0.7
          npm install --save hexo-theme-landscape@0.0.3
          npm install --save hexo-wordcount@6.0.1
          npm install --save or@0.2.0
          npm install --save pjax@0.2.8
          npm install -g yarn@1.22.19

      - name: 部署博客
        run: |
          hexo clean && hexo g
          cd ./public
          git init
          git config user.name "${{secrets.GIT_NAME}}"
          git config user.email "${{secrets.GIT_EMAIL}}"
          git add .
          git commit -m "Update"
          git config --global user.name "miaopasixx"
          git config --global user.email "a13026588708@163.com"
          git push --force --quiet "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF}}" master:master
