name: 自动部署 Hexo

on:
  push:
    branches:
      - main # 修改为你使用的分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 开始运行
        uses: actions/checkout@v1

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: 配置 Git 环境
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "eallion"
          git config --global user.email "eallion@eallion.com"

      - name: 安装 Hexo CLI
        run: 
          npm install hexo-cli -g
          npm install
          npm audit fix # 可选，修复依赖安全漏洞

      - name: 安装 Hexo 插件
        run: 
          npm install hexo-deployer-git hexo-generator-archive hexo-generator-category hexo-generator-feed hexo-generator-index hexo-generator-search hexo-generator-tag \
            hexo-renderer-ejs hexo-renderer-marked hexo-renderer-stylus hexo-server hexo-wordcount --save
          npm audit fix --only=prod # 可选，修复依赖安全漏洞

      - name: 部署博客
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GH_TOKEN }}
          GIT_NAME: ${{ secrets.GIT_NAME }} # 修改为您的用户名或昵称
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }} # 修改为您的邮箱地址
          DEPLOY_BRANCH: gh-pages # 修改为您使用的分支名称
        run: 
          rm -rf .deploy_git
          hexo g -d
          rm ~/.ssh/id_rsa

